<?php

namespace Container3dSPiVo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YTmo1oMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yTmo1oM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yTmo1oM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answer' => ['privates', '.errored..service_locator.yTmo1oM.App\\Entity\\Answer', NULL, 'Cannot autowire service ".service_locator.yTmo1oM": it references class "App\\Entity\\Answer" but no such service exists.'],
        ], [
            'answer' => 'App\\Entity\\Answer',
        ]);
    }
}
