<?php

namespace Container3dSPiVo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QIXMdAEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qIXMdAE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qIXMdAE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answerRepository' => ['privates', 'App\\Repository\\AnswerRepository', 'getAnswerRepositoryService', true],
            'question' => ['privates', '.errored..service_locator.qIXMdAE.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.qIXMdAE": it references class "App\\Entity\\Question" but no such service exists.'],
        ], [
            'answerRepository' => 'App\\Repository\\AnswerRepository',
            'question' => 'App\\Entity\\Question',
        ]);
    }
}
