<?php

namespace Container3dSPiVo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.M5VHZDo.App\Entity\Result' shared service.
     *
     * @return \App\Entity\Result
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.M5VHZDo": it references class "App\\Entity\\Result" but no such service exists.');
    }
}
