<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3dSPiVo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3dSPiVo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3dSPiVo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3dSPiVo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3dSPiVo\App_KernelDevDebugContainer([
    'container.build_hash' => '3dSPiVo',
    'container.build_id' => '40f079b3',
    'container.build_time' => 1619980413,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3dSPiVo');
